######################################################################
# GitLab CI build script for the MUSIT frontend project              #
######################################################################

stages:
  - test

test:
  stage: test
  tags:
    - docker
    - shared
  image: registry.gitlab.com/musit-norway/docker-node

  cache:
    paths:
      - node_modules/

  before_script:
    - apt-get update -qq && apt-get install -qy libelf1

  script:
    - echo "Running frontend tests..."
    - npm install
    - npm run flow
    # Check formatting
    - npm run formatcode
    - git status
    - git diff --exit-code src/ || (echo "ERROR The codebase isn't formatted! See list of files above"; false)